### ISSUE TITLE
User Stories - English Version

### ISSUE THREAD

**Issue by spammenotinoz** [Licoy/ChatGPT-Midjourney-Pro#4]
Boss, great demo experience.  Do you have an English Version?
For the Pro version are the front-end files editable, so I translate myself?
I can't join the group, any other way to communicate?  Located in Australia.
Thank-you

**Comment by Licoy** [comment]
@spammenotinoz There is currently no English version available, and the international version is currently being planned. If it is updated, you can @ you again
